apiVersion: ako.vmware.com/v1beta1
kind: AviInfraSetting
metadata:
  name: my-infrasetting
spec:
  seGroup:
    name: sub-group
  network:
    vipNetworks:
      - networkName: vks-datapath-02
        cidr: 172.18.109.0/24
    enableRhi: false
    nodeNetworks:
      - networkName: vks-workload-01
        cidrs: 
          - 172.18.101.0/24


