apiVersion: v1
kind: Pod
metadata:
  name: nslookup-pod
  namespace: default
spec:
  containers:
  - image: busybox:1.34
    name: busybox
    command: ["nslookup"]
    args: ["tkgs-harbor.tanzu.lab"]
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: "RuntimeDefault"
  imagePullSecrets:
  - name: repocred
  restartPolicy: Never
