kind: Service
apiVersion: v1
metadata:
  labels:
    app: minio
  name: minio
    #  annotations:
    #    ako.vmware.com/load-balancer-ip: 10.200.50.120
spec:
  selector:
    app: minio
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 9090
  type: LoadBalancer
    #  loadBalancerClass: ako.vmware.com/avi-lb
