kind: Service
apiVersion: v1
metadata:
  name: telegraf
  namespace: tanzu-system-telegraf
spec:
  selector:
    app.kubernetes.io/name: telegraf-ds
  ports:
  - name: http
    #    nodePort: 32035
    port: 80
    protocol: TCP
    targetPort: 9723
  type: LoadBalancer
  #loadBalancerClass: ako.vmware.com/avi-lb
