apiVersion: v1
kind: Secret
metadata:
  name: my-vm-bootstrap-data
  namespace: comm-ns
stringData:
  user-data: |
    #cloud-config

    package_update: true
    package_upgrade: true

    ssh:
      emit_keys_to_console: false

    no_ssh_fingerprints: true

    ssh_pwauth: true
    users:
      - name: vmware-system-user
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: false
        # Password set to Admin!23
        passwd: '$6$8jLYuI5uLgpuEVFc$uFlPBmFOVodfWb59VJHISwJncbCWjyeWdIPaHLHfTZiQokYHfxOBUwwSjlEqALbsNTORvF2QM3YeI6vUCmOif/'
        shell: /bin/bash

    package_update: true

    apt:
      sources:
        influxdata.list:
          source: deb [arch=amd64] https://repos.influxdata.com/debian stable main
          keyid: 9D539D90D3328DC7D6C8D3B9D8FF8E1F7DF8B07E

    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - wget
      - influxdb2
      - influxdb2-cli
      - net-tools
      - zip
      - jq

    disk_setup:
      /dev/sdb:
        table_type: gpt
        layout: True
        overwrite: True

    fs_setup:
      - device: /dev/sdb
        filesystem: ext4
        partition: 1

    mounts:
      - [ /dev/sdb1, /data, "auto", "defaults,noexec,nofail" ]

    write_files:
      - path: /etc/ca.cert
        content: |
          -----BEGIN CERTIFICATE-----
          MIIDnzCCAoegAwIBAgIUZQMPDupI+fnwEMGm0rTMEo6Z2rIwDQYJKoZIhvcNAQEL
          BQAwXzELMAkGA1UEBhMCS1IxDjAMBgNVBAgMBXNlb3VsMQ4wDAYDVQQHDAVzZW91
          bDEOMAwGA1UECgwFZXRlY2gxDDAKBgNVBAsMA2VuZzESMBAGA1UEAwwJdGFuenUu
          bGFiMB4XDTI1MDYwNDA5MjQwNVoXDTMwMDYwMzA5MjQwNVowXzELMAkGA1UEBhMC
          S1IxDjAMBgNVBAgMBXNlb3VsMQ4wDAYDVQQHDAVzZW91bDEOMAwGA1UECgwFZXRl
          Y2gxDDAKBgNVBAsMA2VuZzESMBAGA1UEAwwJdGFuenUubGFiMIIBIjANBgkqhkiG
          9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoHm7UW76knCAYeARK0BL4Lc4bDpuzf4BoI1n
          MHmKhnlY0g1EzLKAQQ/E9QCeu5eBVx9TF/zJVLupUc6WarbnP1cqRsU5SB/YCpW5
          FmJVDI5/QGwz18E4+b3JNq6UBSpXT04EizU/bLkzbAPsncukS4HywYqHfyTGlWPT
          xRFIqLBizX3jd8NV0UTMlNf1SsSqADY8MpIJsZHP2ZSHkLqduDzHNbXyIr5THBGH
          x4ZSz4IkKtrVe+loh5PTNmeYS8uosFPZrYRh8axsaiMvvrlR6WODz9qZSgHSri+I
          2yG6FV5skvDrwIh1wQ/x68drSlVtQpg1l8jqzxbjKnum6nQuyQIDAQABo1MwUTAd
          BgNVHQ4EFgQU8OseylCqgrjrbho3fKZ0yFv6mbAwHwYDVR0jBBgwFoAU8OseylCq
          grjrbho3fKZ0yFv6mbAwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
          AQEAZwzKjnOxEjL+d/bkZwnSpo2oDJHJvF/oZH8CxvGgt4NlNox3tjD2+Tp/tgzC
          cKUpbEjdPVaEPmT2h6GUo5b13A9VoFYJIy2dP+z9kkrIABaizPeYxfMPebJq8sWx
          cdTx8qP64QODNDkwVQutCKd1tWcm6P+ppVeFfIit0W6n5LLrRocQCaf/omxkW+KP
          zbsjRLI6y2GmP1J4rr7Cicxb/7YYK7FTKXCuygQ58jgIZo0lO7K3sPiQ2EF7w2Yf
          pTnwDnDhMWB4aGeAtZBIYlAx+WTZToOdyWMaq6NaXp4qbkwtcLsgCNUctFb6jLln
          bOg+P+KlCL6x10scCz0fDJW5IQ==
          -----END CERTIFICATE-----
        owner: 'root:root'
        permissions: '0444'
      - path: /etc/ca.key
        content: |
          -----BEGIN PRIVATE KEY-----
          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCgebtRbvqScIBh
          4BErQEvgtzhsOm7N/gGgjWcweYqGeVjSDUTMsoBBD8T1AJ67l4FXH1MX/MlUu6lR
          zpZqtuc/VypGxTlIH9gKlbkWYlUMjn9AbDPXwTj5vck2rpQFKldPTgSLNT9suTNs
          A+ydy6RLgfLBiod/JMaVY9PFEUiosGLNfeN3w1XRRMyU1/VKxKoANjwykgmxkc/Z
          lIeQup24PMc1tfIivlMcEYfHhlLPgiQq2tV76WiHk9M2Z5hLy6iwU9mthGHxrGxq
          Iy++uVHpY4PP2plKAdKuL4jbIboVXmyS8OvAiHXBD/Hrx2tKVW1CmDWXyOrPFuMq
          e6bqdC7JAgMBAAECggEAFq9uuAHQwT/PHkbvFmal81PjUYVnIY6dS0WCB1u/Jehk
          knkWtzsqn0fr51iZl9pAigDfHb559ZT7yBlEsTw+73jSfKOnx9bckw58Vjo7XKWO
          PpytLXxeogtetPCz8xD7u7XDNaym1SdPKh9Z5SqjBJuPpiV/pw0bV4X/q1WYqGPh
          VsbtQwXnnUBWjgbZpK8dKlcxZZu23y8VVNl9hPPcz4+hDY9bvlZv5npA0RKiKv0A
          GF+D+pql+ZX2qjYs38nbBtrM0UebvFVr+2BXGSvSt3dTSDVj5gdHDCeNWT7R6VyT
          HbsqCHSGcFrEBH/9x56Q3BWHNoqsUuLJLArMaE9u6QKBgQDfl9+Xbq3FxFHJGfBM
          2bGdkUWOeZ6C2adLmbpQL2rRAwUbCHuLfEZZCDW/XaoJpZC/3aqynV/Ex764FGo3
          H+x4szpKh20zRcELIE64k9iBfX2sPgEPdkYpSUUVW+vXdiVJcm6erH9v9KRZ44ni
          O4y+zvGcjTjOdhMuNeTE2PhLxQKBgQC3u/WkTvY81NfUJkwYzshOpEnQZIuPfsLy
          Vq6BbDA1ZSsOJFjGPS8zUgNmSDEcSRgBdsyfUnc4ckivasAMFBoFmEYuQPOFtxCU
          CnI7sEMCQyOQ3xPTbZlXF9UlgprHzLvr+mj3/rOSj6MjcaTNuJpUKKxn/eydIG8n
          WCZL4idzNQKBgQDFOyDeYaEjvKMwM5NHFxiYF1c18I4ken4aMAarSMh+ip1sVTU1
          u3AKhTV0Etk1HTjsJkq2uB+MY24WzttKuPxNFDwtFfz7p2I7wEnwg2oN/3ZmA2PI
          Edqd/KXVy3nkW7FUcn6ltR/M0A5RxGcSitkCT2XNZL1hUcJlluCvy3xqyQKBgBhv
          ev/bMIxukjW40i4KckFjQB3jAVyYMz0foh28Ub0IM22yD8xtnrVoluMnfsCQSA0J
          y7T0tr5fFKOfwuLYWY2c7th/8uM5sY6+xOqDSqYmX7iIso5P6TDYDpTqhcNEy0lb
          CFLTIPbA+6VfG9fwUTYYIrXB45ISGjZVVuKItU5xAoGAB6wB7Ba3hR7QUhvSlwkY
          0NBLqhuGWhEL1fW81ME7pbMfUnTWsSvRnzxVq1WvhlT1clTysjUMdvx+QuC5cMjD
          MNX/HvlAa1fktwuS6+kjO4rqG8bsGm+uJLbwihqKrOvelnFnqNWtDG8em6ECvKEb
          3nChcWo4WLrdeIS2tLnXz1w=
          -----END PRIVATE KEY-----
        owner: 'root:root'
        permissions: '0444'
      - path: /influxdb/certs/v3.ext
        content: |
          authorityKeyIdentifier=keyid,issuer
          basicConstraints=CA:FALSE
          keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
          extendedKeyUsage = serverAuth
          subjectAltName = @alt_names
          [alt_names]
          DNS.1=influxdb.tanzu.lab
        owner: root:root
        permissions: '0644'
    runcmd:
      - mkdir -p /influxdb/certs
      - mkdir -p /data/influxdbv2/engine
      - openssl genrsa -out /influxdb/certs/influxdb.key 4096
      - openssl req -sha512 -new -subj "/C=KR/ST=Seoul/L=Seoul/O=Eng/OU=Personal/CN=influxdb.tanzu.lab" -key /influxdb/certs/influxdb.key -out /influxdb/certs/influxdb.csr
      - openssl x509 -req -sha512 -days 365 -extfile /influxdb/certs/v3.ext -CA /etc/ca.cert -CAkey /etc/ca.key -CAcreateserial -in /influxdb/certs/influxdb.csr -out /influxdb/certs/influxdb.crt
      - chown influxdb:influxdb /influxdb/certs/influxdb.crt
      - chown influxdb:influxdb /influxdb/certs/influxdb.key
      - chown -R influxdb:influxdb /data/influxdbv2
      - echo "bolt-path = \"/var/lib/influxdb/influxd.bolt\"" > /etc/influxdb/config.toml
      - echo "tls-cert = \"/influxdb/certs/influxdb.crt\"" >> /etc/influxdb/config.toml
      - echo "tls-key = \"/influxdb/certs/influxdb.key\""  >> /etc/influxdb/config.toml
      - echo "engine-path = \"/data/influxdbv2/engine\""  >> /etc/influxdb/config.toml
      - systemctl daemon-reload
      - systemctl restart influxdb
      - influx setup --username telegrafuser --password 'VMware1!' --org VMware --bucket Supervisor --retention 168h --token '52FkpcOX71DCRQBfXtA68L1zuRyoY2KvC7aG6uCgoEOJzseRmRHOaUxrPO1jIj11KUuAZYZKdPeTitD3j0cM4Z8HT2' --force --host https://localhost:8086 --skip-verify
