apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineService
metadata:
  name: influxdb-vm
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8086
  selector:
    vm.name: influxdb-vm
  type: LoadBalancer
#  loadBalancerIP: 10.0.130.100
