apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: keycloak
    meta.helm.sh/release-namespace: keycloak
  creationTimestamp: "2025-06-27T01:45:02Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: 26.2.5
    helm.sh/chart: keycloak-24.7.4
  name: keycloak
  namespace: keycloak
  resourceVersion: "6793"
  uid: dc825ab5-34dd-43e8-be2d-9efa8cf85af1
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.9.131
  clusterIPs:
  - 172.20.9.131
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 10.10.152.201
  ports:
  - name: http
    nodePort: 30492
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 31635
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
