apiVersion: v1
kind: Secret
metadata:
  name: my-vm-secret
  namespace: ichoi-ns01
stringData:
  user-data: |
    #cloud-config
    password: VMware1!
    users:
    - default
    - name: viadmin
      sudo: ['ALL=(ALL) NOPASSWD:ALL']
      groups: sudo
      shell: /bin/bash
        #ssh_authorized_keys:
        #- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSL7uWGj...
    runcmd:
    - echo viadmin:VMware1! | /usr/sbin/chpasswd
    - sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/g" /etc/ssh/sshd_config
    - service ssh reload
    write_files:
    - path: /etc/my-plaintext
      permissions: '0644'
      owner: root:root
      content: |
        Hello, world.
