# istio:
#   ambientMode:
#     enabled: false
#     ztunnel:
#       resources:
#         limits:
#           cpu: ""
#           memory: ""
#         requests:
#           cpu: 200m
#           memory: 512Mi
#   enableStrictMTLS: false
#   gateways:
#     egress:
#       autoscaling:
#         enabled: false
#         maxReplicas: 5
#         minReplicas: 1
#       enabled: false
#       namespace: istio-egress
#       priorityClassName: ""
#       replicas: 1
#       resources:
#         limits:
#           cpu: 2000m
#           memory: 1024Mi
#         requests:
#           cpu: 100m
#           memory: 128Mi
#     ingress:
#       autoscaling:
#         enabled: false
#         maxReplicas: 5
#         minReplicas: 1
#       enabled: false
#       namespace: istio-ingress
#       priorityClassName: ""
#       replicas: 1
#       resources:
#         limits:
#           cpu: 2000m
#           memory: 1024Mi
#         requests:
#           cpu: 100m
#           memory: 128Mi
#   istioCNI:
#     enabled: true
#     resources:
#       limits:
#         cpu: ""
#         memory: ""
#       requests:
#         cpu: 100m
#         memory: 100Mi
#   meshConfig:
#     accessLogFile: /dev/stdout
#     connectTimeout: 10s
#     enableDNSProxy: false
#     enablePrometheusMerge: true
#     enableTracing: true
#     ingressControllerMode: STRICT
#     ingressSelector: ingressgateway
#     meshID: ""
#     meshMTLS:
#       minProtocolVersion: TLSV1_2
#     proxy:
#       resources:
#         limits:
#           cpu: 2000m
#           memory: 1024Mi
#         requests:
#           cpu: 100m
#           memory: 128Mi
#     trustDomain: cluster.local
#     trustDomainAliases: []
#     waypoint:
#       resources:
#         limits:
#           cpu: "2"
#           memory: 1Gi
#         requests:
#           cpu: 100m
#           memory: 128Mi
#   namespace: istio-system
#   pilot:
#     autoscaling:
#       enabled: false
#       maxReplicas: 5
#       minReplicas: 1
#     priorityClassName: ""
#     replicas: 1
#     resources:
#       limits:
#         cpu: ""
#         memory: ""
#       requests:
#         cpu: 500m
#         memory: 2048Mi
#   support:
#     priorityClassName: ""
#     resources:
#       limits:
#         cpu: 250m
#         memory: 256Mi
#       requests:
#         cpu: 100m
#         memory: 64Mi
