grafana:
  config:
    #! Refer to https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file
    datasource_yaml: |-
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          # prometheus namespace
          url: http://prometheus-server.tanzu-system-monitoring.svc.cluster.local
          access: proxy
          tlsSkipVerify: true
          isDefault: true
  deployment:
    replicas: 1
    updateStrategy: Recreate
  pvc:
    storageClassName: tanzu-storage-policy
    accessMode: ReadWriteOnce
    storage: 10Gi
  secret:
    admin_password: YWRtaW4=
    admin_user: YWRtaW4=
    type: Opaque
  service:
    port: 80
    targetPort: 3000
    type: LoadBalancer
ingress:
  enabled: false
  prefix: /
  servicePort: 80
  virtual_host_fqdn: grafana.system.tanzu
    #  tlsCertificate:
    #    tls:
    #      crt:
    #      key:
namespace: tanzu-system-dashboards
