apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: pkg-contour
  namespace: contour-ingress
spec:
  serviceAccountName: contour-sa
  packageRef:
    refName: contour.kubernetes.vmware.com
    versionSelection:
      constraints: 1.30.3+vmware.1-vks.1
  values:
  - secretRef:
      name: contour-data-values
